# Generated by Django 5.2.6 on 2025-09-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='long',
            new_name='lng',
        ),
    ]
