# Generated by Django 5.2.6 on 2025-09-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
