# Generated by Django 5.2.6 on 2025-09-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_alter_address_email_alter_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
