# Generated by Django 5.2.6 on 2025-09-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_shoppingcart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='delivery_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_product_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
