# Generated by Django 5.2.6 on 2025-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shoppingcart_delivery_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='status',
            field=models.CharField(default='در حال پردازش', max_length=64),
        ),
    ]
