# Generated by Django 5.2.6 on 2025-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_paymentoption_shoppingcart_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
