# Generated by Django 5.2.6 on 2025-10-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_shoppingcart_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='card_number',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
