# Generated by Django 5.2.6 on 2025-09-18 11:48

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('service', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BindingDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BindingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DesignOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProductOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_from', models.IntegerField(blank=True, null=True)),
                ('with_number', models.BooleanField(default=True)),
                ('design_requirement', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=orders.models.invoice_file_path)),
                ('status', models.CharField(default='در حال چاپ', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_services', models.ManyToManyField(blank=True, to='orders.additionalservice')),
                ('binding_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bindingdirection')),
                ('binding_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bindingtype')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.color')),
                ('invoice_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.invoiceproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
