# Generated by Django 5.2.6 on 2025-09-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_hex',
            field=models.CharField(default='#c42b59', max_length=32),
        ),
    ]
