# Generated by Django 5.2.6 on 2025-09-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_color_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproductorder',
            name='numbering_location',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
