# Generated by Django 5.2.6 on 2025-09-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_invoiceproductorder_numbering_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproductorder',
            name='color',
            field=models.CharField(default='red', max_length=64),
        ),
    ]
