# Generated by Django 5.2.6 on 2025-09-19 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_invoiceproductorder_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_hex',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='invoiceproductorder',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.color'),
        ),
    ]
