# Generated by Django 5.2.6 on 2025-09-19 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_color_hex_color_code_rename_color_color_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproductorder',
            name='id_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceproductorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_product_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
