# Generated by Django 5.2.6 on 2025-09-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_invoiceproductorder_id_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceproductorder',
            old_name='id_paid',
            new_name='is_paid',
        ),
    ]
