# Generated by Django 5.2.6 on 2025-09-23 09:20

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_id_paid_invoiceproductorder_is_paid'),
        ('products', '0004_sidetype_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerProductOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('design_requirement', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('file_front', models.FileField(blank=True, null=True, upload_to=orders.models.flyer_file_path)),
                ('file_back', models.FileField(blank=True, null=True, upload_to=orders.models.flyer_file_path)),
                ('status', models.CharField(default='در حال چاپ', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_services', models.ManyToManyField(blank=True, to='orders.additionalservice')),
                ('flyer_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.flyerproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flyer_product_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
