# Generated by Django 5.2.6 on 2025-09-23 15:04

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_flyerproductorder'),
        ('products', '0006_alter_flyerproduct_slug_alter_invoiceproduct_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionProductOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('glue_attach', models.BooleanField(default=True)),
                ('design_requirement', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=orders.models.prescription_file_path)),
                ('status', models.CharField(default='در حال چاپ', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_services', models.ManyToManyField(blank=True, to='orders.additionalservice')),
                ('binding_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.bindingdirection')),
                ('perscription_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.prescriptionproduct')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perscription_product_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
