# Generated by Django 5.2.6 on 2025-09-23 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_prescriptionproductorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionproductorder',
            old_name='perscription_product',
            new_name='prescription_product',
        ),
        migrations.AlterField(
            model_name='prescriptionproductorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_product_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
