# Generated by Django 5.2.6 on 2025-09-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shoppingcart_is_paid_shoppingcart_paid_at_and_more'),
        ('orders', '0011_rename_perscription_product_prescriptionproductorder_prescription_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionproductorder',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.shoppingcart'),
        ),
    ]
