# Generated by Django 5.2.6 on 2025-09-24 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_shoppingcart_user_and_more'),
        ('orders', '0012_prescriptionproductorder_shopping_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyerproductorder',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flyer_orders', to='cart.shoppingcart'),
        ),
        migrations.AddField(
            model_name='invoiceproductorder',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_orders', to='cart.shoppingcart'),
        ),
        migrations.AlterField(
            model_name='prescriptionproductorder',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_orders', to='cart.shoppingcart'),
        ),
    ]
