# Generated by Django 5.2.6 on 2025-09-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_flyerproductorder_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flyerproductorder',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='invoiceproductorder',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='prescriptionproductorder',
            name='is_paid',
        ),
    ]
