# Generated by Django 5.2.6 on 2025-09-18 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CirculationPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circulation', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('base_price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('circulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.circulationprint')),
                ('invoice_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.invoicetype')),
                ('paper_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.papersize')),
                ('paper_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.papertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
