# Generated by Django 5.2.6 on 2025-09-20 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sidetype_flyerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('base_price', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('circulation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.circulationprint')),
                ('paper_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.papersize')),
                ('paper_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.papertype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
