# Generated by Django 5.2.6 on 2025-09-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_prescriptionproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidetype',
            name='num',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
