# Generated by Django 5.2.6 on 2025-09-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sidetype_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='flyerproduct',
            name='color_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colormode'),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='color_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colormode'),
        ),
        migrations.AddField(
            model_name='prescriptionproduct',
            name='color_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.colormode'),
        ),
    ]
