# Generated by Django 5.2.6 on 2025-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_colormode_flyerproduct_color_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyerproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='prescriptionproduct',
            name='slug',
            field=models.CharField(blank=True, max_length=128, unique=True),
        ),
    ]
